swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST API Test
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /{londonloc}/londonpeople:
    get:
      operationId: people.read_london
      tags:
        - People
      summary: Return people listed as in or location within 50 miles of London
      description: Returns people who are listed as either living in London, or whose current coordinates are within 50 miles of London
      parameters:
        - name: londonloc
          in: path
          type: string
          required: true
          default: "listed"
          description: People listed as located in London (path = 'listed') or people with coordinates showing they are located within 50 miles of London (path = 'within50'). 
      responses:
        200:
          description: Successfully read user list operation
          schema:
            type: array
            items:
              properties:
                id:
                  type: integer
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                ip_address: 
                  type: string
                latitude:
                  type: number
                longitude:
                  type: number
               
                
